package sepe.webservicessepe;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100408.1504.05443)

@WebServiceClient(wsdlLocation="https://apps.ika.gr/WebServicesSepeNew-WebServicesSepe-context-root/WebServicesMainMethodSoap12HttpPort?WSDL",
  targetNamespace="http://webservicessepe/", name="WebServicesMainMethodService")
public class WebServicesMainMethodService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("webservicessepe.WebServicesMainMethodService");
      URL baseUrl = WebServicesMainMethodService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            WebServicesMainMethodService.class.getResource("https://apps.ika.gr/WebServicesSepeNew-WebServicesSepe-context-root/WebServicesMainMethodSoap12HttpPort?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://apps.ika.gr/WebServicesSepeNew-WebServicesSepe-context-root/WebServicesMainMethodSoap12HttpPort?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "https://apps.ika.gr/WebServicesSepeNew-WebServicesSepe-context-root/WebServicesMainMethodSoap12HttpPort?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://apps.ika.gr/WebServicesSepeNew-WebServicesSepe-context-root/WebServicesMainMethodSoap12HttpPort?WSDL",
          e);
    }
  }

  public WebServicesMainMethodService()
  {
    super(wsdlLocationURL,
          new QName("http://webservicessepe/", "WebServicesMainMethodService"));
  }

  public WebServicesMainMethodService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="WebServicesMainMethodPort")
  public WebServicesMainMethod getWebServicesMainMethodPort()
  {
    return (WebServicesMainMethod) super.getPort(new QName("http://webservicessepe/",
                                                                           "WebServicesMainMethodPort"),
                                                                 WebServicesMainMethod.class);
  }

  @WebEndpoint(name="WebServicesMainMethodPort")
  public WebServicesMainMethod getWebServicesMainMethodPort(WebServiceFeature... features)
  {
    return (WebServicesMainMethod) super.getPort(new QName("http://webservicessepe/",
                                                                           "WebServicesMainMethodPort"),
                                                                 WebServicesMainMethod.class,
                                                                 features);
  }
}
