create or replace public synonym af2_attachments for sp_int.af2_attachments;
create or replace public synonym eg_e3 for sp_erg.eg_e3;
create or replace public synonym eg_e4 for sp_erg.eg_e4;
create or replace public synonym eg_e4_empl_det for sp_erg.eg_e4_empl_det;
create or replace public synonym eg_e5 for sp_erg.eg_e5;
create or replace public synonym eg_e6 for sp_erg.eg_e6;
create or replace public synonym eg_e7 for sp_erg.eg_e7;
create or replace public synonym eg_e8 for sp_erg.eg_e8;
create or replace public synonym eg_e8_det for sp_erg.eg_e8_det;
create or replace public synonym eg_e9 for sp_erg.eg_e9;
create or replace public synonym eg_e9_det for sp_erg.eg_e9_det;
create or replace public synonym eg_rt_identity_types for sp_erg.eg_rt_identity_types;
create or replace public synonym eg_rt_sepe for sp_erg.eg_rt_sepe;
create or replace public synonym hr_vw_departments for sp_hr.hr_vw_departments;
create or replace public synonym hr_vw_employees for sp_hr.hr_vw_employees;
create or replace public synonym ik_employer for sp_ika.ik_employer;
create or replace public synonym ik_employer_branches for sp_ika.ik_employer_branches;
create or replace public synonym ik_employer_incharges for sp_ika.ik_employer_incharges;
create or replace public synonym ik_rt_taxation_offices for sp_ika.ik_rt_taxation_offices;
create or replace public synonym int_vw_rec_difference for sp_int.int_vw_rec_difference;
create or replace public synonym ra_erg_e3e5 for sp_cas.ra_erg_e3e5;
create or replace public synonym ra_erg_e3e6 for sp_cas.ra_erg_e3e6;
create or replace public synonym ra_erg_empl_prf for sp_cas.ra_erg_empl_prf;
create or replace public synonym ra_erg_or_tm for sp_cas.ra_erg_or_tm;
create or replace public synonym ra_erg_stats for sp_cas.ra_erg_stats;
create or replace public synonym rg_emp_branches for sp_reg.rg_emp_branches;
create or replace public synonym rg_employer for sp_reg.rg_employer;
create or replace public synonym rg_vw_emp_branches for sp_reg.rg_vw_emp_branches;
create or replace public synonym rg_vw_emp_incharges for sp_reg.rg_vw_emp_incharges;
create or replace public synonym rg_vw_employer for sp_reg.rg_vw_employer;
create or replace public synonym rg_vw_employer_stakod for sp_reg.rg_vw_employer_stakod;
create or replace public synonym rg_vw_ie_reg for sp_reg.rg_vw_ie_reg;
create or replace public synonym sp_rt_accident_severity for sp_sp.sp_rt_accident_severity;
create or replace public synonym sp_rt_accident_type for sp_sp.sp_rt_accident_type;
create or replace public synonym sp_rt_affected_position for sp_sp.sp_rt_affected_position;
create or replace public synonym sp_rt_affected_severity for sp_sp.sp_rt_affected_severity;
create or replace public synonym sp_rt_affected_time for sp_sp.sp_rt_affected_time;
create or replace public synonym sp_rt_affected_type for sp_sp.sp_rt_affected_type;
create or replace public synonym sp_rt_complaint_matter for sp_sp.sp_rt_complaint_matter;
create or replace public synonym sp_rt_cooperation_type for sp_sp.sp_rt_cooperation_type;
create or replace public synonym sp_rt_degree_type for sp_sp.sp_rt_degree_type;
create or replace public synonym sp_rt_educ_level for sp_sp.sp_rt_educ_level;
create or replace public synonym sp_rt_erg_marital_status for sp_sp.sp_rt_erg_marital_status;
create or replace public synonym sp_rt_erg_sex for sp_sp.sp_rt_erg_sex;
create or replace public synonym sp_rt_identity_type for sp_sp.sp_rt_identity_type;
create or replace public synonym sp_rt_ie_speciality for sp_sp.sp_rt_ie_speciality;
create or replace public synonym sp_rt_kallikratis for sp_sp.sp_rt_kallikratis;
create or replace public synonym sp_rt_lad_applicant_type for sp_sp.sp_rt_lad_applicant_type;
create or replace public synonym sp_rt_lad_application_type for sp_sp.sp_rt_lad_application_type;
create or replace public synonym sp_rt_lad_subjects for sp_sp.sp_rt_lad_subjects;
create or replace public synonym sp_rt_lad_violations for sp_sp.sp_rt_lad_violations;
create or replace public synonym sp_rt_nationality for sp_sp.sp_rt_nationality;
create or replace public synonym sp_rt_oaed for sp_sp.sp_rt_oaed;
create or replace public synonym sp_rt_prog_oaed for sp_sp.sp_rt_prog_oaed;
create or replace public synonym sp_rt_request_delivery for sp_sp.sp_rt_request_delivery;
create or replace public synonym sp_rt_residence_permit for sp_sp.sp_rt_residence_permit;
create or replace public synonym sp_rt_speciality for sp_sp.sp_rt_speciality;
create or replace public synonym sp_rt_stakod for sp_sp.sp_rt_stakod;
create or replace public synonym sp_rt_subject_area for sp_sp.sp_rt_subject_area;
create or replace public synonym sp_rt_subject_group for sp_sp.sp_rt_subject_group;
create or replace public synonym sp_rt_ta_speciality for sp_sp.sp_rt_ta_speciality;
create or replace public synonym sp_rt_violations_gateg for sp_sp.sp_rt_violations_gateg;
create or replace public synonym sp_rt_witness_type for sp_sp.sp_rt_witness_type;
create or replace public synonym sp_rt_yde for sp_sp.sp_rt_yde;
create or replace public synonym sp_rta_documents_receiver for sp_sp.sp_rta_documents_receiver;
create or replace synonym sp_cas.hr_vw_departments for sp_hr.hr_vw_departments;
create or replace synonym sp_cas.hr_vw_employees for sp_hr.hr_vw_employees;
create or replace synonym sp_cas.ik_rt_taxation_offices for sp_ika.ik_rt_taxation_offices;
create or replace synonym sp_cas.int_vw_accident for sp_int.int_vw_accident;
create or replace synonym sp_cas.int_vw_accident_witness for sp_int.int_vw_accident_witness;
create or replace synonym sp_cas.int_vw_complaint for sp_int.int_vw_complaint;
create or replace synonym sp_cas.int_vw_illness for sp_int.int_vw_illness;
create or replace synonym sp_cas.int_vw_lab_difference for sp_int.int_vw_lab_difference;
create or replace synonym sp_cas.int_vw_lad_subjects for sp_int.int_vw_lad_subjects;
create or replace synonym sp_cas.pap_update_case_id for sp_int.pap_update_case_id;
create or replace synonym sp_cas.sp_rt_kallikr_dept_sepe for sp_sp.sp_rt_kallikr_dept_sepe;
create or replace synonym sp_cas.sp_rt_kallikratis for sp_sp.sp_rt_kallikratis;
create or replace synonym sp_cas.sp_rt_stakod for sp_sp.sp_rt_stakod;
create or replace synonym sp_esk.hr_vw_departments for sp_hr.hr_vw_departments;
create or replace synonym sp_esk.hr_vw_employees for sp_hr.hr_vw_employees;
create or replace synonym sp_esk.ik_rt_taxation_offices for sp_ika.ik_rt_taxation_offices;
create or replace synonym sp_esk.int_vw_accident for sp_int.int_vw_accident;
create or replace synonym sp_esk.int_vw_complaint for sp_int.int_vw_complaint;
create or replace synonym sp_esk.int_vw_illness for sp_int.int_vw_illness;
create or replace synonym sp_esk.int_vw_lab_difference for sp_int.int_vw_lab_difference;
create or replace synonym sp_esk.int_vw_protocol for sp_int.int_vw_protocol;
create or replace synonym sp_esk.sp_rt_kallikr_dept_sepe for sp_sp.sp_rt_kallikr_dept_sepe;
create or replace synonym sp_esk.sp_rt_kallikratis for sp_sp.sp_rt_kallikratis;
create or replace synonym sp_int.sp_cm_vw_cases_docs for sp_cas.sp_cm_vw_cases_docs;
create or replace synonym sp_int.sp_hr_vw_departments for sp_int.hr_vw_departments;
create or replace synonym sp_int.sp_hr_vw_employees for sp_int.hr_vw_employees;
create or replace synonym sp_int.sp_rt_kallikr_dept_sepe for sp_sp.sp_rt_kallikr_dept_sepe;
create or replace synonym sp_int.sp_rt_kallikratis for sp_sp.sp_rt_kallikratis;
create or replace synonym sp_int.hr_vw_department for sp_hr.hr_vw_department;
CREATE OR REPLACE EDITIONABLE SYNONYM "SP_PTL"."SN_FUNC_INT_CALCULATE_TA_HOURS" FOR "SP_INT"."CALCULATE_TA_HOURS";
CREATE OR REPLACE EDITIONABLE SYNONYM "SP_PTL"."SN_PROC_CALLGGDEWS" FOR "SP_REG"."CALLGGDEWS";
CREATE OR REPLACE EDITIONABLE SYNONYM "SP_PTL"."SN_SP_RG_GGDE_MHTRWO" FOR "SP_REG"."RG_GGDE_MHTRWO";