REM INSERTING into SP_PTL.SP_PTL_WORKPLACE_DOCTOR
SET DEFINE OFF;
Insert into SP_PTL.SP_PTL_WORKPLACE_DOCTOR (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (0,55,'11111190',null,'324234234');
Insert into SP_PTL.SP_PTL_WORKPLACE_DOCTOR (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (584,584,'0123456789',null,'null');
Insert into SP_PTL.SP_PTL_WORKPLACE_DOCTOR (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (1724,1724,null,null,null);
Insert into SP_PTL.SP_PTL_WORKPLACE_DOCTOR (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (1727,1727,null,null,null);
Insert into SP_PTL.SP_PTL_WORKPLACE_DOCTOR (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (583,582,null,null,null);
Insert into SP_PTL.SP_PTL_WORKPLACE_DOCTOR (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (1521,1521,'777777777',null,null);
