REM INSERTING into SP_PTL.SP_PTL_SAFETY_TECHNICIAN
SET DEFINE OFF;
Insert into SP_PTL.SP_PTL_SAFETY_TECHNICIAN (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (4,444,'1111112',null,'2222222');
Insert into SP_PTL.SP_PTL_SAFETY_TECHNICIAN (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (1721,1721,null,null,null);
Insert into SP_PTL.SP_PTL_SAFETY_TECHNICIAN (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (1725,1725,null,null,null);
Insert into SP_PTL.SP_PTL_SAFETY_TECHNICIAN (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (1726,1726,null,null,null);
Insert into SP_PTL.SP_PTL_SAFETY_TECHNICIAN (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (1730,1730,null,null,null);
Insert into SP_PTL.SP_PTL_SAFETY_TECHNICIAN (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (13401,13401,null,null,null);
Insert into SP_PTL.SP_PTL_SAFETY_TECHNICIAN (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (13162,13162,null,null,null);
Insert into SP_PTL.SP_PTL_SAFETY_TECHNICIAN (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (1735,1735,null,null,null);
Insert into SP_PTL.SP_PTL_SAFETY_TECHNICIAN (ID,USER_ID,AFM,CARD_TYPE,CARD_NUMBER) values (13161,13161,null,null,null);
